#!/bin/python

world_name = 'SmoWorld'

worlds[world_name] = '/home/pfsmorigo/.minecraft/saves/'+world_name
outputdir = '/mnt/disk/beirut/minecraft/overviewer/'+world_name
rendermode = "smooth_lighting"

MC_IDS = {
    0: "air",
    1: "stone",
    2: "grass",
    3: "dirt",
    4: "cobblestone",
    5: "planks",
    6: "sapling",
    7: "bedrock",
    8: "flowing water",
    9: "water",
    10: "flowing lava",
    11: "lava",
    12: "sand",
    13: "gravel",
    14: "gold ore",
    15: "iron ore",
    16: "coal ore",
    17: "log",
    18: "leaves",
    19: "sponge",
    20: "glass",
    21: "lapis ore",
    22: "lapis block",
    23: "dispenser",
    24: "sandstone",
    25: "noteblock",
    26: "bed",
    27: "golden rail",
    28: "detector rail",
    29: "sticky piston",
    30: "web",
    31: "tallgrass",
    32: "deadbush",
    33: "piston",
    34: "piston head",
    35: "wool",
    36: "piston extension",
    37: "yellow flower",
    38: "red flower",
    39: "brown mushroom",
    40: "red mushroom",
    41: "gold block",
    42: "iron block",
    43: "double stone slab",
    44: "stone slab",
    45: "brick block",
    46: "tnt",
    47: "bookshelf",
    48: "mossy cobblestone",
    49: "obsidian",
    50: "torch",
    51: "fire",
    52: "mob spawner",
    53: "oak stairs",
    54: "chest",
    55: "redstone wire",
    56: "diamond ore",
    57: "diamond block",
    58: "crafting table",
    59: "wheat",
    60: "farmland",
    61: "furnace",
    62: "lit furnace",
    63: "standing sign",
    64: "wooden door",
    65: "ladder",
    66: "rail",
    67: "stone stairs",
    68: "wall sign",
    69: "lever",
    70: "stone pressure plate",
    71: "iron door",
    72: "wooden pressure plate",
    73: "redstone ore",
    74: "lit redstone ore",
    75: "unlit redstone torch",
    76: "redstone torch",
    77: "stone button",
    78: "snow layer",
    79: "ice",
    80: "snow",
    81: "cactus",
    82: "clay",
    83: "reeds",
    84: "jukebox",
    85: "fence",
    86: "pumpkin",
    87: "netherrack",
    88: "soul sand",
    89: "glowstone",
    90: "portal",
    91: "lit pumpkin",
    92: "cake",
    93: "unpowered repeater",
    94: "powered repeater",
    95: "stained glass",
    96: "trapdoor",
    97: "monster egg",
    98: "stonebrick",
    99: "brown mushroom block",
    100: "red mushroom block",
    101: "iron bars",
    102: "glass pane",
    103: "melon block",
    104: "pumpkin stem",
    105: "melon stem",
    106: "vine",
    107: "fence gate",
    108: "brick stairs",
    109: "stone brick stairs",
    110: "mycelium",
    111: "waterlily",
    112: "nether brick",
    113: "nether brick fence",
    114: "nether brick stairs",
    115: "nether wart",
    116: "enchanting table",
    117: "brewing stand",
    118: "cauldron",
    119: "end portal",
    120: "end portal frame",
    121: "end stone",
    122: "dragon egg",
    123: "redstone lamp",
    124: "lit redstone lamp",
    125: "double wooden slab",
    126: "wooden slab",
    127: "cocoa",
    128: "sandstone stairs",
    129: "emerald ore",
    130: "ender chest",
    131: "tripwire hook",
    132: "tripwire",
    133: "emerald block",
    134: "spruce stairs",
    135: "birch stairs",
    136: "jungle stairs",
    137: "command block",
    138: "beacon",
    139: "cobblestone wall",
    140: "flower pot",
    141: "carrots",
    142: "potatoes",
    143: "wooden button",
    144: "skull",
    145: "anvil",
    146: "trapped chest",
    147: "light weighted pressure plate",
    148: "heavy weighted pressure plate",
    149: "unpowered comparator",
    150: "powered comparator",
    151: "daylight detector",
    152: "redstone block",
    153: "quartz ore",
    154: "hopper",
    155: "quartz block",
    156: "quartz stairs",
    157: "activator rail",
    158: "dropper",
    159: "stained hardened clay",
    160: "stained glass pane",
    161: "leaves2",
    162: "log2",
    163: "acacia stairs",
    164: "dark oak stairs",
    165: "slime",
    166: "barrier",
    167: "iron trapdoor",
    168: "prismarine",
    169: "sea lantern",
    170: "hay block",
    171: "carpet",
    172: "hardened clay",
    173: "coal block",
    174: "packed ice",
    175: "double plant",
    176: "standing banner",
    177: "wall banner",
    178: "daylight detector inverted",
    179: "red sandstone",
    180: "red sandstone stairs",
    181: "double stone slab2",
    182: "stone slab2",
    183: "spruce fence gate",
    184: "birch fence gate",
    185: "jungle fence gate",
    186: "dark oak fence gate",
    187: "acacia fence gate",
    188: "spruce fence",
    189: "birch fence",
    190: "jungle fence",
    191: "dark oak fence",
    192: "acacia fence",
    193: "spruce door",
    194: "birch door",
    195: "jungle door",
    196: "acacia door",
    197: "dark oak door",
    # ...and items.
    256: "iron shovel",
    257: "iron pickaxe",
    258: "iron axe",
    259: "flint and steel",
    260: "apple",
    261: "bow",
    262: "arrow",
    263: "coal",
    264: "diamond",
    265: "iron ingot",
    266: "gold ingot",
    267: "iron sword",
    268: "wooden sword",
    269: "wooden shovel",
    270: "wooden pickaxe",
    271: "wooden axe",
    272: "stone sword",
    273: "stone shovel",
    274: "stone pickaxe",
    275: "stone axe",
    276: "diamond sword",
    277: "diamond shovel",
    278: "diamond pickaxe",
    279: "diamond axe",
    280: "stick",
    281: "bowl",
    282: "mushroom stew",
    283: "golden sword",
    284: "golden shovel",
    285: "golden pickaxe",
    286: "golden axe",
    287: "string",
    288: "feather",
    289: "gunpowder",
    290: "wooden hoe",
    291: "stone hoe",
    292: "iron hoe",
    293: "diamond hoe",
    294: "golden hoe",
    295: "wheat seeds",
    296: "wheat",
    297: "bread",
    298: "leather helmet",
    299: "leather chestplate",
    300: "leather leggings",
    301: "leather boots",
    302: "chainmail helmet",
    303: "chainmail chestplate",
    304: "chainmail leggings",
    305: "chainmail boots",
    306: "iron helmet",
    307: "iron chestplate",
    308: "iron leggings",
    309: "iron boots",
    310: "diamond helmet",
    311: "diamond chestplate",
    312: "diamond leggings",
    313: "diamond boots",
    314: "golden helmet",
    315: "golden chestplate",
    316: "golden leggings",
    317: "golden boots",
    318: "flint",
    319: "porkchop",
    320: "cooked porkchop",
    321: "painting",
    322: "golden apple",
    323: "sign",
    324: "wooden door",
    325: "bucket",
    326: "water bucket",
    327: "lava bucket",
    328: "minecart",
    329: "saddle",
    330: "iron door",
    331: "redstone",
    332: "snowball",
    333: "boat",
    334: "leather",
    335: "milk bucket",
    336: "brick",
    337: "clay ball",
    338: "reeds",
    339: "paper",
    340: "book",
    341: "slime ball",
    342: "chest minecart",
    343: "furnace minecart",
    344: "egg",
    345: "compass",
    346: "fishing rod",
    347: "clock",
    348: "glowstone dust",
    349: "fish",
    350: "cooked fish",
    351: "dye",
    352: "bone",
    353: "sugar",
    354: "cake",
    355: "bed",
    356: "repeater",
    357: "cookie",
    358: "filled map",
    359: "shears",
    360: "melon",
    361: "pumpkin seeds",
    362: "melon seeds",
    363: "beef",
    364: "cooked beef",
    365: "chicken",
    366: "cooked chicken",
    367: "rotten flesh",
    368: "ender pearl",
    369: "blaze rod",
    370: "ghast tear",
    371: "gold nugget",
    372: "nether wart",
    373: "potion",
    374: "glass bottle",
    375: "spider eye",
    376: "fermented spider eye",
    377: "blaze powder",
    378: "magma cream",
    379: "brewing stand",
    380: "cauldron",
    381: "ender eye",
    382: "speckled melon",
    383: "spawn egg",
    384: "experience bottle",
    385: "fire charge",
    386: "writable book",
    387: "written book",
    388: "emerald",
    389: "item frame",
    390: "flower pot",
    391: "carrot",
    392: "potato",
    393: "baked potato",
    394: "poisonous potato",
    395: "map",
    396: "golden carrot",
    397: "skull",
    398: "carrot on a stick",
    399: "nether star",
    400: "pumpkin pie",
    401: "fireworks",
    402: "firework charge",
    403: "enchanted book",
    404: "comparator",
    405: "netherbrick",
    406: "quartz",
    407: "tnt minecart",
    408: "hopper minecart",
    409: "prismarine shard",
    410: "prismarine crystals",
    411: "rabbit",
    412: "cooked rabbit",
    413: "rabbit stew",
    414: "rabbit foot",
    415: "rabbit hide",
    416: "armor stand",
    417: "iron horse armor",
    418: "golden horse armor",
    419: "diamond horse armor",
    420: "lead",
    421: "name tag",
    422: "command block minecart",
    423: "mutton",
    424: "cooked mutton",
    425: "banner",
    427: "spruce door",
    428: "birch door",
    429: "jungle door",
    430: "acacia door",
    431: "dark oak door",
    2256: "record 13",
    2257: "record cat",
    2258: "record blocks",
    2259: "record chirp",
    2260: "record far",
    2261: "record mall",
    2262: "record mellohi",
    2263: "record stal",
    2264: "record strad",
    2265: "record ward",
    2266: "record 11",
    2267: "record wait"
}

def signFilter(poi):
    if poi['id'] == 'Sign':
        return "\n".join([poi['Text1'], poi['Text2'], poi['Text3'], poi['Text4']])

def chestFilter(poi):
    global MC_IDS
    if poi['id'] == 'Chest':
        items = ''
        for item in poi['Items']:
            item_name = MC_IDS[item['id']]
            items += '\n%s (%d)' % (item_name, item['Count'])

            if 'diamond' in item_name:
                print 'FOUND: %s at %d, %d, %d' % (item_name, poi['x'], poi['y'], poi['z'])

        return ('Chest', 'Chest with %d items (%d, %d, %d):%s' % (len(poi['Items']), poi['x'], poi['y'], poi['z'], items))

def playerFilter(poi):
    if poi['id'] == 'Player':
        poi['icon'] = "http://overviewer.org/avatar/%s" % poi['EntityId']
        return "Last known location for %s" % poi['EntityId']

def townFilter(poi):
    if poi['id'] == 'Town':
        try:
            return (poi['name'], poi['description'])
        except KeyError:
            return poi['name'] + '\n'

def get_crop(radius = 0):
    center_x = -16
    center_z = -76
    castle_radius = 30
    min_x = center_x-castle_radius-radius
    min_z = center_z-castle_radius-radius
    max_x = center_x+castle_radius+radius+1
    max_z = center_z+castle_radius+radius+1
    return (min_x, min_z, max_x, max_z)

filters = [dict(name = "Signs", filterFunction = signFilter),
           dict(name = "Chests", filterFunction = chestFilter, checked = True),
           dict(name = "Players", filterFunction = playerFilter)]

renders['overworld_daytime'] = {
        'world': world_name,
        'title': 'Castle',
        'dimension': 'overworld',
        'northdirection': 'upper-left',
        'crop': get_crop(100),
        'markers': filters
        }

renders['overworld_daytime'] = {
        'world': world_name,
        'title': 'Day',
        'dimension': 'overworld',
        'northdirection': 'upper-left',
        'crop': get_crop(100),
        'markers': filters
        }

renders['overworld_night'] = {
        'world': world_name,
        'title': 'Night',
        'rendermode': 'smooth_night',
        'dimension': 'overworld',
        'northdirection': 'upper-left',
        'crop': get_crop(100),
        'markers': filters
        }

for i in range(0, 15):
    renders['overworld_level_'+str(i)] = {
            'world': world_name,
            'title': 'Level '+str(i),
            'rendermode': [Base(), EdgeLines(), SmoothLighting(), Depth(max = (i*8)+3)],
            'dimension': 'overworld',
            'northdirection': 'upper-left',
            'crop': get_crop(),
            'markers': filters
            }

renders['nether'] = {
        'world': world_name,
        'title': 'Nether',
        'rendermode': 'nether',
        'dimension': 'nether',
        'northdirection': 'upper-left',
        'crop': get_crop(),
        'markers': filters
        }
